### PR TITLE
CARGO-1595: add test to validate the wait for the process to complete

### PR DESCRIPTION
**Pull request by educhastenier**
By the way, improve the way to redirect process.getInputStream() to outputFile (if set).
Indeed, this way, there is no need to create a new Thread to write Java command output,
which avoids this asynchronous mechanism that could lead to Java command terminate before
the output is redirected.

Relates to https://codehaus-cargo.atlassian.net/browse/CARGO-1595

Before the fix (756b46faca24ea9538d977fcf5f385566ee5d44e), output of the new test was:

```
org.codehaus.cargo.util.CargoException: Cannot read JVM version, please check that the provided execution [/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -version] is valid

    at org.codehaus.cargo.container.spi.AbstractInstalledLocalContainer.createJvmLauncher(AbstractInstalledLocalContainer.java:397)
    at org.codehaus.cargo.container.spi.AbstractInstalledLocalContainer.startInternal(AbstractInstalledLocalContainer.java:294)
    at org.codehaus.cargo.container.spi.InstalledLocalContainerTest.testJvmVersionSlowToExecute(InstalledLocalContainerTest.java:579)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at junit.framework.TestCase.runTest(TestCase.java:164)
    at junit.framework.TestCase.runBare(TestCase.java:130)
    at junit.framework.TestResult$1.protect(TestResult.java:106)
    at junit.framework.TestResult.runProtected(TestResult.java:124)
    at junit.framework.TestResult.run(TestResult.java:109)
    at junit.framework.TestCase.run(TestCase.java:120)
    at junit.textui.TestRunner.doRun(TestRunner.java:121)
    at com.intellij.junit3.JUnit3IdeaTestRunner.doRun(JUnit3IdeaTestRunner.java:128)
    at junit.textui.TestRunner.doRun(TestRunner.java:114)
    at com.intellij.junit3.JUnit3IdeaTestRunner.startRunnerWithArgs(JUnit3IdeaTestRunner.java:49)
    at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
    at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:18)
    at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
    at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
    at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.io.IOException: Can't read JVM version from output: Picked up JAVA_TOOL_OPTIONS: -Dtest=foo

    at org.codehaus.cargo.container.spi.AbstractInstalledLocalContainer.createJvmLauncher(AbstractInstalledLocalContainer.java:388)
    ... 21 more
java.io.IOException: Can't read JVM version from output: Picked up JAVA_TOOL_OPTIONS: -Dtest=foo

    at org.codehaus.cargo.container.spi.AbstractInstalledLocalContainer.createJvmLauncher(AbstractInstalledLocalContainer.java:388)
    at org.codehaus.cargo.container.spi.AbstractInstalledLocalContainer.startInternal(AbstractInstalledLocalContainer.java:294)
    at org.codehaus.cargo.container.spi.InstalledLocalContainerTest.testJvmVersionSlowToExecute(InstalledLocalContainerTest.java:579)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at junit.framework.TestCase.runTest(TestCase.java:164)
    at junit.framework.TestCase.runBare(TestCase.java:130)
    at junit.framework.TestResult$1.protect(TestResult.java:106)
    at junit.framework.TestResult.runProtected(TestResult.java:124)
    at junit.framework.TestResult.run(TestResult.java:109)
    at junit.framework.TestCase.run(TestCase.java:120)
    at junit.textui.TestRunner.doRun(TestRunner.java:121)
    at com.intellij.junit3.JUnit3IdeaTestRunner.doRun(JUnit3IdeaTestRunner.java:128)
    at junit.textui.TestRunner.doRun(TestRunner.java:114)
    at com.intellij.junit3.JUnit3IdeaTestRunner.startRunnerWithArgs(JUnit3IdeaTestRunner.java:49)
    at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
    at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:18)
    at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
    at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
    at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

### CODE REVIEW

**Comment by educhastenier** [comment]
@alitokmen feel free to comment / amend this PR

**Comment by alitokmen** [comment]
Hi @educhastenier 

It is great to see contributions! Thanks a lot!

I believe your valuable contribution can be enhanced by also redirecting the error stream into the file - It would mean though that the `append` parameter would have to be handled differently, i.e. if `append` is `true` then we most likely want to clear the existing file, and both output and error redirects would have the append option.

And, as `DefaultJvmLauncherStreamRedirector` becomes obsolete, you can delete it.

What do you think?

**Comment by educhastenier** [comment]
> if `append` is `true` then we most likely want to clear the existing file, and both output and error redirects would have the append option.

A far as I understand the Process javadoc, this is what `.redirectErrorStream(true)` does.
Moreover, why would we want to clear the existing file if append is `true`? This does not seem obvious to me... To respect the previous implementation with `DefaultJvmLauncherStreamRedirector`, I would say that we do not clear the file, but simply append to the potentially already existing content.

**Comment by alitokmen** [comment]
> > if `append` is `true` then we most likely want to clear the existing file, and both output and error redirects would have the append option.
> 
> A far as I understand the Process javadoc, this is what `.redirectErrorStream(true)` does. Moreover, why would we want to clear the existing file if append is `true`? This does not seem obvious to me... To respect the previous implementation with `DefaultJvmLauncherStreamRedirector`, I would say that we do not clear the file, but simply append to the potentially already existing content.

Well spotted - Then we are good! :) I'll merge your valuable contribution now

**Pull request merged**
