### PR TITLE
Add null check in Tomcat8xStandaloneLocalConfiguration, fix regression introduced in 1.4.19

### PR DESCRIPTION
**Pull request by moparisthebest**
Simple fix, our project was crashing with an NPE here, worked up until 1.4.18.

### CODE REVIEW

**Comment by alitokmen** [comment]
@moparisthebest thanks for your contribution. Can you please let me know, in which case you got a NPE? We could perhaps add a test..

**Comment by moparisthebest** [comment]
I guess our war doesn't have a "extraClasspath" ?  We are using maven-war-plugin 3.2.2 if that helps.  I was just upgrading cargo from 1.4.8 to 1.7.2 and java from 8 to 11 when this started happening, I couldn't figure out what configuration might make it happy so I tracked down and fixed the NPE instead...

**Comment by alitokmen** [comment]
@moparisthebest thanks for your reply - It's awkward this didn't get caught by our integration tests! Do you need a release ASAP or can you wait?

**Comment by moparisthebest** [comment]
I really appreciate the offer, but no need to rush, I built a snapshot locally for us to use until the official release.  The tests don't pass at all for me locally though so I had to [disable](https://github.com/moparisthebest/cargo/commit/98c534d372c7582dce491569f20fbd817675faba) the broken ones to get that far.

**Comment by alitokmen** [comment]
Great, thanks @moparisthebest - I tracked this indeed to be caused by https://codehaus-cargo.atlassian.net/browse/CARGO-1373 / https://github.com/codehaus-cargo/cargo/commit/da40ac487943a99e5cbda53e69cd3d6b60cbc9a1#diff-3bc9358a8165d421fe1a264ea489cebc

**Comment by alitokmen** [comment]
@moparisthebest FYI we just released Codehaus Cargo 1.7.3, and it includes the bugfix you submitted: https://codehaus-cargo.atlassian.net/browse/CARGO-1478

**Pull request merged**
