### PR TITLE
CARGO-1362 - WebLogic: added SSL and logging configuration

### PR DESCRIPTION
**Pull request by sutaakar**
Separated WLST deployer from standalone configuration, small deployer refactoring.

### CODE REVIEW

**Comment by sutaakar** [comment]
Latest error on semaphore looks weird:

testDeployWarStatically (tomcat6x,installed)(org.codehaus.cargo.sample.java.WarCapabilityContainerTest)  Time elapsed: 180.392 sec  <<< ERROR!
org.codehaus.cargo.container.ContainerException: Deployable [http://localhost:60928/cargocpc/index.html] failed to finish deploying within the timeout period [180000]. The Deployable state is thus unknown.

Maybe some temporary error, in PR aren't any Tomcat change.

**Comment by alitokmen** [comment]
Hi Karel

This is weird - And only happens in the Java 5 build.

Do you have a spare machine with a Java 5 VM? Else I'll investigate...

Cheers

S. Ali Tokmen
http://ali.tokmen.com/
http://contact.ali.tokmen.com/

**Comment by alitokmen** [comment]
Hi Karel

It built now - No one knows why it decided to break, maybe something
else on the server was busy!

I'll now merge the branch

Cheers

S. Ali Tokmen
http://ali.tokmen.com/
http://contact.ali.tokmen.com/

**Comment by sutaakar** [comment]
thanks :)

**Pull request merged**
