### PR TITLE
WildFly container implementation refactoring

### PR DESCRIPTION
**Pull request by sutaakar**
Targets of this refactoring are:
- Get rid of direct changes to WildFly configuration files and rather use provided configuration tools - in this case CLI scripts.
- Extends WildFly configuration capabilities - JMS, Mail, XA datasource, custom scripts.
- Try to decouple WildFly implementation from JBoss (partly done) - to get rid of unwanted dependencies.
- Affects so far just InstalledLocalContainers and StandaloneLocalConfigurations.

Future work: implement support for domain mode.

WildFly 9 and 10 implementations use embedded server for resource configuration, for more info see [1]. 

This implementation will fail on current WildFly10.0.0 release as there is a bug for embedded server [2] which prevents redirecting of configuration file to our profile location. This is going to be fixed in WildFly 10.1.0 - which is currently in CR1 build [3]. I hope it will be officially released soon. Until that time I suggest to keep this PR opened.

I still have to review this code for some hidden glitches and leftovers.

@psiroky If you will have some time to spare please look on it.

[1] https://developer.jboss.org/wiki/OfflineCLIWork
[2] https://issues.jboss.org/browse/WFCORE-1373
[3] http://wildfly.org/downloads/

### CODE REVIEW

**Comment by sutaakar** [comment]
Seems that JMS tests, which use standalone-full profile for WildFly, fails on Semaphore. I tried it locally and they works. 
@alitokmen Are you able to see WildFly logs for tests from Semaphore? Would be good to check why it fails.

**Comment by psiroky** [comment]
I quickly skimmed through the changes and it looks good (but I don't have the knowledge about these parts, so take this as a soft +1 :)).

**Comment by alitokmen** [comment]
I think the CI issue was a temporary port problem - I see:

`org.codehaus.cargo.container.ContainerException: Deployable [http://localhost:57980/cargocpc/index.html] failed to finish deploying within the timeout period [180000]. The Deployable state is thus unknown.`

That usually mans a port is busy

**Comment by sutaakar** [comment]
I don't think so, this port is used by all tests, but there were failing just tests using standalone-full.
This issue seems permanent here, saw it in all builds for this PR.

**Comment by alitokmen** [comment]
@sutaakar, let me know if you need the CI to output any log files - I can change job definitions

**Comment by sutaakar** [comment]
@alitokmen I think it isn't needed, seems that I already found what caused the issue. There seems to be issue with writing JMS journal on Semaphore, possibly due to disc encryption. it should be fixed in latest commit here.

**Comment by alitokmen** [comment]
@sutaakar FYI I updated the CI so it outputs WildFly 10 server logs for the couple failing tests, rebuild is now in progress and hopefully helps with the diagnosis 👍

**Comment by alitokmen** [comment]
@sutaakar, the logs on https://semaphoreci.com/codehaus-cargo/cargo/branches/pull-request-61/builds/13 confirm your doubts with regards to file system encryption.

`AMQ222010: Critical IO Error, shutting down the server. file=AIOSequentialFile:/home/runner/cargo/core/samples/java/target/wildfly10x/installed/JmsQueueResourceOnStandaloneConfigurationTest/testUserConfiguresJmsQueueAsResource/container/data/activemq/journal/activemq-data-1.amq.tmp, message=Cannot open file:Invalid argument: java.io.IOException: Cannot open file:Invalid argument`

Do you think switching to NIO as described in https://docs.jboss.org/author/display/WFLY10/AIO+-+NIO+for+messaging+journal would be possible?

**Comment by sutaakar** [comment]
@alitokmen Yes. I already implemented switching to NIO for those JMS tests, see https://github.com/codehaus-cargo/cargo/pull/61/files#diff-e4717272057437a34d0a326c8f297715R129

Problem is that it doesn't correctly affect WildFly10 due to bug for embedded server: https://issues.jboss.org/browse/WFCORE-1373
This issue should be fixed for WildFly10.1.0, which isn't released yet.

**Comment by alitokmen** [comment]
@sutaakar, thanks for the details. Shall I then merge with master?

**Comment by sutaakar** [comment]
Not yet. I would wait until WildFly 10.1 is released, so it will correctly work there too.
In the meantime I will make here some minor enhancements.

**Comment by alitokmen** [comment]
Fair enough, let's then wait - I'll also delay the 1.5.1 release accordingly, as the plan would be to prepare 1.6.0 after the 1.5.1 release.

I also see on https://semaphoreci.com/codehaus-cargo/cargo/branches/pull-request-61/builds/12 that DataSourceOnStandaloneConfigurationTest, MailResourceOnStandaloneConfigurationTest and SystemPropertyCapabilityTest are also failing in the CI; will this also be fixed by WildFly 10.1?

**Comment by alitokmen** [comment]
WildFly 10.1 is now out: http://wildfly.org/news/2016/08/19/WildFly10-1-Released/ 😀

**Comment by sutaakar** [comment]
Ready to be merged now.
It should also work for WildFly10.0 (or EAP 7.0) without any problem.

**Comment by alitokmen** [comment]
Thanks - I can also test on Windows (and Mac)

**Pull request merged**
