### PR TITLE
ignoreFailures and more than one container instance started from maven 

### PR DESCRIPTION
**Pull request by sunnymoon**
Implement support for ignoreFailures on all mojos so that maven can still progress through on integration tests with more than one container domain started - also, allow for the specification of a container unique id so that it becomes possible to start more than one container in a pre-integration-test phase and stop more than one container in a post-integration-test phase

### CODE REVIEW

**Comment by alitokmen** [comment]
Nice patch - Thank you!

Would you be so kind to also create an associated entry in https://codehaus-cargo.atlassian.net/projects/CARGO/ so we have it documented as well?

**Comment by sunnymoon** [comment]
Done - created!
https://codehaus-cargo.atlassian.net/browse/CARGO-1420

**Comment by alitokmen** [comment]
Hi José

Thanks for your contributions :)

I added the `ignoreFailures` and `container.id` parameters to https://codehaus-cargo.atlassian.net/wiki/display/CARGO/Maven2+Plugin+Reference+Guide and also published it on https://codehaus-cargo.github.io/cargo/Maven2+Plugin+Reference+Guide.html#Maven2PluginReferenceGuide-container

Now, you'd have two things to do:

1. Update the `cargo-archetype-multiple-containers` artifact with your new methodology
2. Document it accordingly on https://codehaus-cargo.atlassian.net/wiki/display/CARGO/Maven2+Archetypes#Maven2Archetypes-Archetypeshowingthestartingandstoppingofmultiplecontainerssimultaneously

When do you think you can handle these?

Regards

**Comment by sutaakar** [comment]
Hi Ali,

Thanks for implementation, looks good. About the feature with setting.xml - yes, it would be good to connect them together.

**Comment by alitokmen** [comment]
Hi @sutaakar 

Sure - Change checked in now, documentation on https://codehaus-cargo.github.io/cargo/Maven2+Plugin+Reference+Guide.html also updated.

Cheers

**Pull request merged**
