### PR TITLE
Cargo 1447  http2

### PR DESCRIPTION
**Pull request by cmouttet**
https://codehaus-cargo.atlassian.net/browse/CARGO-1447

### CODE REVIEW

**Comment by alitokmen** [comment]
... checks failed :( @tcollignon have you had time to review?

**Comment by tcollignon** [comment]
Hi @alitokmen

This is related to my recent changes? Or you need help for other things?

**Comment by alitokmen** [comment]
sorry @tcollignon I tagged the wrong person :(

@cmouttet have you had the time to review the changes you've done? the CI says the ANT-based builds fail, perhaps an issue with default values or the container versions where the properties apply

**Comment by cmouttet** [comment]
@alitokmen I'm looking at it right now. :)

**Comment by cmouttet** [comment]
The CI run is passing now the `ANT` step, but there is another issue now. I don't understand the current state of the CI. JRE-6 broke at integration test `cargo-daemon-itests-deployable-on-tomcat`, JRE-6+ is still running since more than one hour. It displaying late steps as green with time 0:00. Looks like the CI build is in an instable state.

**Comment by cmouttet** [comment]
@alitokmen can you please try to build it? I have no idea how to proceed. Thanks

**Comment by alitokmen** [comment]
@cmouttet do you have a machine with an actual JDK 6 to perform a real build and see the actual logs from the build?

**Comment by cmouttet** [comment]
I forced a new CI build. I'ts running now.

**Comment by alitokmen** [comment]
@cmouttet now indeed it seems to be progressing well :)

**Comment by alitokmen** [comment]
@cmouttet I'm now reviewing the code - The changes are rather impressive, and very clever! Well done :)

I have very little points:

* `MissingXmlElementAppender.java` and `MissingXmlElementAppenderTest.java` have the copyright headers missing
* The `MissingXmlElementAppender` class is not marked as public

**Comment by alitokmen** [comment]
@cmouttet thanks - The CI also passed :)

For your question regarding class visibility: we (for now) always put all classes as `public`, even when they're utilities. It sometimes helped...

Now, one more code question from my side: I see you used a `LinkedHashMap` in `AbstractStandaloneLocalConfiguration.java`, is there a reason for it?

Another slight comment: I _think_ we never used `@since` yet :) That'll be a first, I'm hoping it doesn't break other things related to Javadoc / release (if it does, I might have to remove it :().

Otherwise, the rest looks very, very, very good! I really appreciate the way you improved XML handling, very neat!

Would you like to add a page in Confluence to explain how to use the new properties `TomcatPropertySet.CONNECTOR_PROTOCOL_CLASS`, `TomcatPropertySet.CONNECTOR_SSL_IMPLEMENTATION_NAME` and `TomcatPropertySet.CCONNECTOR_HTTP_UPGRADE_PROTOCOL`

**Comment by cmouttet** [comment]
@alitokmen OK, `MissingXmlElementAppender` is public now. Regarding the `LinkedHashMap`, I thought about the order of the replacements is important. Maybe it's not the case, then using a simple `HashMap` is fine, the unit tests will point it out...

And yes, I can add the description of the properties to Confluence. Even the startStopThread I added before.

**Comment by cmouttet** [comment]
I didn't find a proper place to put the documentation, the draft is now a sub page of ScratchWiki.
https://codehaus-cargo.atlassian.net/wiki/spaces/CARGO/pages/476119041?atlOrigin=eyJpIjoiMjUxZTdkYmJhY2ViNDZjODg0NzI5MjRlYWJkNThlZjQiLCJwIjoiYyJ9

**Pull request merged**
