### PR TITLE
CARGO-1453: Improve Loading of Jar in Tomcat when Using Resources Mecanism

### PR DESCRIPTION
**Pull request by tcollignon**
Hi, this PR intend to fix https://codehaus-cargo.atlassian.net/projects/CARGO/issues/CARGO-1453, and like I said in the last comment, fix the actual bug in Tomcat8xStandaloneLocalConfiguration#configureExtraClasspathToken because the wrong xml tag if added if the tag "Resources" is not present in context.xml file. I think an additionnal test will be great to detect this error.

### CODE REVIEW

**Comment by alitokmen** [comment]
Thanks for the patch - Unfortunately some changes don’t compile on Java 6, can you recheck?

**Comment by tcollignon** [comment]
Hi @alitokmen ,

Yes I check that, but unfortunately I think this is not my PR.

See the error : 

```
[ERROR] Failed to execute goal org.codehaus.cargo:cargo-maven2-plugin:1.6.10-SNAPSHOT:start (start) on project cargo-sample-maven2-jetty7x-embedded-test: Failed to resolve dependency: Could not transfer artifact org.eclipse.jdt.core.compiler:ecj:jar:3.5.1 from/to central (https://repo.maven.apache.org/maven2): Received fatal alert: protocol_version
[ERROR] org.eclipse.jdt.core.compiler:ecj:jar:3.5.1
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR] central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] -> [Help 1]
```

I think it's maven central communication (I thought they have changed something in SSL

**Comment by alitokmen** [comment]
@tcollignon you are right - Triggering a rebuild solved it. Shall I merge?

**Comment by tcollignon** [comment]
Cool
I must test this on windows, so I need more time please
And maybe I need to add a test for the bug I found no ?

**Comment by alitokmen** [comment]
@tcollignon of course - I'll then wait for your signal to merge :) Happy coding!

**Comment by tcollignon** [comment]
thx, I have test on windows and it's OK.
But now I try to add a test who cover the bug, but I'm not sure that it's correct, on my mac it doesn't pass for now

**Comment by tcollignon** [comment]
Hi @alitokmen , I don't understand errors from semaphoreci, can you help me please?

Thx

**Comment by alitokmen** [comment]
Sure - The `--fail-at-end` makes errors counterintuitive (I've unset it now).

The error is in _Cargo Samples for Java_, the following test case fails: `testLoadClassOnWarWithContextXmlFile (tomcat7x,installed)(org.codehaus.cargo.sample.java.tomcat.WarExtraClasspathWithContextTest)`

**Comment by tcollignon** [comment]
Ok so it's the same of my local test
Do you have any idea of why this fail ? the code actually works, so I don't understand why the test fail

**Comment by tcollignon** [comment]
Oh I got it, I improve test testLoadClassOnWarWithContextXmlFile, but this is the testLoadClassOnExpandedWarWithContextXmlFile one, I update the PR with the fix

**Comment by alitokmen** [comment]
Indeed the CI takes time as it tests ALL (tens of!) containers...

**Comment by alitokmen** [comment]
Tests now passed, would you consider the work finished at this stage?

**Comment by tcollignon** [comment]
Oh ok nice  !

Yes you can merge it, I have finish on this

Have you a plan to release cargo soon ?

Thx

**Comment by alitokmen** [comment]
Thanks 🙏 

We ideally have one release every two months; perhaps then end of September or early October. Do you need any earlier or do you plan to provide any new functionalities / patches?

**Comment by tcollignon** [comment]
If you can do this previously on september it's good for me, because I have plan to work on eclipse IDE for my dev team before Java 11 (end of september)

thx

**Pull request merged**
