### PR TITLE
CARGO-1367 : fix 2 possibles bugs with tomcat 8 Resources

### PR DESCRIPTION
**Pull request by tcollignon**
Classes defined before libs, are not loading before libs
Directory declared contains many jars

See : https://codehaus-cargo.atlassian.net/browse/CARGO-1367

### CODE REVIEW

**Comment by tcollignon** [comment]
Maybe it make sense to add tests on this, but I don't know How to to this.

**Comment by alitokmen** [comment]
Hi Thomas

Thanks for the patch. We typically add container-specific tests in the "samples" module, where "real life container tests" are done.

You can see the Tomcat-specific ones in https://github.com/codehaus-cargo/cargo/tree/master/core/samples/java/src/test/java/org/codehaus/cargo/sample/java/tomcat and to run simply execute:

mvn clean install -Ptomcat8x

Cheers

**Comment by tcollignon** [comment]
Ok for integration-tets I will try.
And for unit test where can I put it ? (which name), because Tomcat8xStandaloneLocalConfigurationTest is still usiing, and I can't add test in it right?

**Comment by alitokmen** [comment]
Hi Thomas

Tomcat8xStandaloneLocalConfigurationTest is in the Tomcat container module - Which means when you test the Tomcat container is not there.

In the Samples module, the tests actually download the container (so, Tomcat 8.x binaries) and can configure it - So, "real life" containers tests would be better there.

Cheers

**Comment by tcollignon** [comment]
Ok
I have found your test WarExtraClasspathTest, and it's look be good, it test jar case.

You confirm that it's running even in tomcat 8?

Thanks

**Comment by alitokmen** [comment]
Hi Thomas

Yes, it does: See https://semaphoreci.com/codehaus-cargo/cargo (you can also access it via the Continous Integration link on the Codehaus Cargo web site).

Regards

**Pull request merged**
